# Generated by Django 2.1.2 on 2018-11-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tagList',
            new_name='tag_list',
        ),
    ]
