# Generated by Django 2.1.2 on 2018-11-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181105_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='audioUrl',
            new_name='audio_url',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='favoritesCount',
            new_name='favorites_count',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
